project:
  type: website

website:
  title: "Handbook of Recognition and Rewards"
  favicon: public/favicon.png
  # cover-image: cover.png
  navbar:
    logo: public/RR_logo_handbook.png
    background: "#0080c9"
    logo-alt: "UNL-RR-default"
    title: false
    collapse-below: lg
    left:
      - text: "Policies"
        menu:
          - text: All
            file: all_universities.qmd
      - text: Guides
        file: recommendation.qmd
    tools:
      - icon: github
        href: https://github.com/sanlifaez/Awesome-Recognition-and-Rewards/public_engagement_roles
        text: Handbook of Recognition and Rewards
      # - icon: rss
      #   href: https://quarto.org/docs/blog/index.xml
      #   text: Quarto Blog RSS
  site-url: https://sanlifaez.github.io/Awesome-Recognition-and-Rewards/public_engagement_roles
  repo-url: https://github.com/sanlifaez/Awesome-Recognition-and-Rewards/public_engagement_roles
  issue-url: https://github.com/sanlifaez/Awesome-Recognition-and-Rewards/public_engagement_roles/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  page-footer:
    left:
      - text: "CC0 Public Domain Dedication"
        href: "https://creativecommons.org/publicdomain/zero/1.0/legalcode"
    right:
      - text: "NEWS, UNL-RR"
bibliography: references.bib

format:
  html:
    toc: true
    theme:
      - cosmo # https://bootswatch.com/
      - custom.scss # https://quarto.org/docs/output-formats/html-themes.html#theme-options
    code-copy: true
    code-overflow: wrap
